Allow tempdir/tempfile as instance methods
dagolden/Path-Tiny pull request #242
Opened 2021-10-01 19:45 UTC by polettix

This patch allows using methods tempdir/tempfile as instance methods too, in addition to class methods and simple functions.

When used as instance methods, the underlying instance MUST represent a directory. In this case, it is used to override the DIR option of File::Temp.

The documentation makes a reference to the version when the added behavior is made available, I don't know if this wanted.

This pull request addresses #115

2021-10-01 20:12 UTC, polettix commented
One thing, to be transparent: any `DIR` option passed is ignored in this case, i.e. the directory-as-object always wins.

If this not the wanted behavior it's easy (although not trivial) to change this, although in this case I would expect the programmer to use the class method or the exported function.

2021-10-01 21:14 UTC, xdg commented
Thanks.  I'm a bit busy with family obligations lately, but I'll try to make time this weekend or next week to review it.

2021-10-03 14:51 UTC, polettix commented
> Thanks. I'm a bit busy with family obligations lately, but I'll try to make time this weekend or next week to review it.

No worries and no pressure - it's voluntary open source (and it's not a security bug) 😄

2021-10-20 12:14 UTC, xdg requested changes
This looks great -- I wish I'd done this originally.  I have a couple minor requests. Also, I'd like to see a test of the leading options hash to get more coverage of the refactored code paths.  (Doing a coverage test on the new code looking for other gaps would be a good idea.)

2021-10-20 12:14 UTC, xdg commented on t/temp.t
> +subtest "tempdir w/ leading template as instance method" => sub {
Typo:  "w/o leading template"

2021-10-20 12:14 UTC, xdg commented on t/temp.t
> +    my $tempfile = $repodir->tempfile("helloXXXXX", DIR => '/');
If buggy, this would fail because `/` isn't writeable.  Better to use `$basedir`, I think.

2021-10-20 16:28 UTC, polettix commented on t/temp.t
> +subtest "tempdir w/ leading template as instance method" => sub {
Sure

2021-10-20 22:14 UTC, closed without merging

2021-10-20 22:15 UTC, xdg commented
Thank you very much!  Shipping a dev release to CPAN now.